name: Trigger auto deployment for auditservice

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/auditservice-AutoDeployTrigger-65e8ccde-372e-4fd0-9a42-d55a93031563.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AUDITSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUDITSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUDITSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.AUDITSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUDITSERVICE_REGISTRY_PASSWORD }}
          containerAppName: auditservice
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: mtarmidi/auditservice:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


