name: Build & Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up commit SHA as image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/audit-service:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/audit-service:${{ env.TAG }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/audit-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/audit-service:${{ env.TAG }}
